### PR TITLE
Fix bad color suggestions near corners

### LINKED ISSUE #1: Color suggestion fails with a particular shade of green
Hi!

Noticed this while using a11y-color in a side-project. Here's a repro:

I added the following to `test/color.js`:

```js
describe("with a white foreground and a light green background", () => {
  it("returns a dark green", () => {
    let fg = parseColor("rgb(255, 255, 255)");
    let bg = parseColor("rgb(2, 184, 117)");

    let suggestions = suggestColors(bg, fg, {
      AA: 3.0,
      AAA: 4.5,
    });

    expect(suggestions.AA.contrast).to.be.at.least(2.95);
    expect(suggestions.AAA.contrast).to.be.at.least(4.45);
  });
});
```

`npm test` then fails with the following:

```
  1) suggestColors with a white foreground and a light green background returns a dark green:
     AssertionError: expected '2.91' to be at least 2.95
      at Context.<anonymous> (test/color.js:91:48)
```

It seems `suggestColors` is sending me back a ratio of 2.91 and 3.91 when I ask for 3.0 and 4.5 respectively.

This also seems to be a problem in accessibility developer tools: http://jsbin.com/voluwoqezo/edit?html,js,console

### PR DESCRIPTION
**Pull request by alice**
Fixes #1 

@jessebeach @jdan @ckundo PTAL

### CODE REVIEW

File: src/color.js [hunk 1]
```diff
@@ -366,34 +365,40 @@ function translateColor (ycc, luma) {
...
   let intersection = null;
 
-  for (let i = 0; i < cubeFaces.length; i++) {
-    let cubeFace = cubeFaces[i];
-    intersection = findIntersection(line, cubeFace);
+  let cubeFaces = (lighter ? YCC_CUBE_FACES_WHITE : YCC_CUBE_FACES_BLACK);
+  for (let cubeFace of cubeFaces) {
+    let candidateIntersection = findIntersection(line, cubeFace);
+    if (candidateIntersection.z < 0 || candidateIntersection.z > 1)
+      continue;
```
Comment (jdan) [inline src/color.js:372]: At first I thought this was reworking line 373 from the before column, but I'm unable to follow the logic here.

File: src/color.js [hunk 2]
```diff
@@ -366,34 +365,40 @@ function translateColor (ycc, luma) {
...
-  }
 
-  if (intersection.x != ycc.x || intersection.y != ycc.y) {
+  if (intersection.x != ycc.x || intersection.y != ycc.y)
     throw "Intersection has wrong Cb/Cr values.";
-  }
 
-  if (Math.abs(endpoint.luma - intersection.luma) < Math.abs(endpoint.luma - luma)) {
-    let translatedColor = [luma, ycc.Cb, ycc.Cr];
+  // If luma is closer to endpoint than intersection.luma is, point is outside cube.
```
Comment (jdan) [inline src/color.js:391]: Thanks for the comment here 👍

**Review by jdan — COMMENTED** [review]
Thank you thank you! I'm unfamiliar with the original impl, so feel free to take my one inline comment with a grain of salt. The unit test passing is plenty of evidence for me.

File: src/color.js (hunk 1 above)
Comment (alice) [reply src/color.js:372]: This section is the crux of the change.

Have a look at these two slides: 
https://docs.google.com/presentation/d/1wNR8g-mhAcbU_g-5S4FJ749b4Tn5KhIw3zA-RFunylo/edit#slide=id.g63d390087_1_363
https://docs.google.com/presentation/d/1wNR8g-mhAcbU_g-5S4FJ749b4Tn5KhIw3zA-RFunylo/edit#slide=id.g63d390087_1_383

When changing the luma, it's easy for the resulting coordinates to fall outside the cube. That would result in a "colour" with a value for `r`, `g` or `b` which is not within `[0, 255]`, i.e. not an actual colour. So, we need to clip the colour to the nearest side of the cube.

We do this by taking the three planes representing the three sides of the cube in the direction from the original point that we want to travel, i.e. lighter (towards white, which is `(0, 0, 1)`) or darker (towards black, `(0, 0, 0)`), and finding the intersection between the vertical line containing the original point and the nearest plane.

Originally, I assumed that the first intersection we found which has a `z`/`luma` value between 0 and 1 was ok. However, I forgot to take into account that - of course - those planes continue out past the edges of the cube.

So, the bug you found was from finding an intersection with a plane from the *wrong side* of the cube, which wasn't actually *on* the cube, simply because of the order in which we were testing for intersections. Hence, we were ending up with a negative value for `r`.

This change changes it so that we're checking *all three* potential sides, and making sure we pick the intersection which is closest to the original point.

So now this line, instead of breaking out of the loop, simply checks whether this is a *plausible* intersection (i.e. has a `z`/`luma` value which falls within the range of the cube).

Then, lines 381-382 ensure that we find the *right* intersection.

Comment (jdan) [reply src/color.js:372]: 👍 Thanks for the explanation

**Review by jdan — APPROVED** [review]
Wonderful stuff, thank you @alice!

**Comment by jdan** [comment]
@jessebeach could you publish a new version to npm when you get a chance? Or add `@prezjordan` as a collaborator and I'd be happy to do it :)

**Comment by jessebeach** [comment]
I'd rather have more folks with the power to publish so I'm not a bottleneck. Adding you as a collaborator. Just give me a minute to figure out how to do that via npm :)

**Comment by jessebeach** [comment]
@prezjordan can you DM me on Twitter (@jessebeach) with your email address that you use on NPM?

**Comment by jessebeach** [comment]
@alice do you want publishing powers as well? Send me your NPM email address
